comment:
  require_changes: yes
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
parsers:
  javascript:
    enable_partials: yes
