comment:
  require_changes: yes
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
parsers:
  javascript:
    enable_partials: yes
ignore:
  - "admin"
  - "**/src/*Db"
