# This file is meant to extend docker-compose.yml for development environment
version: '2'
services:

  apartments-api:
    ports:
      - '5858:5858'
    volumes:
      - ./apartments-api/src:/home/nodejs/app/src
    environment:
      NODE_ENV: local
    command: bash -c "npm install --silent && npm run start:dev"

  front-gateway:
    ports:
      - '5859:5859'
      - '8888:8888'
    volumes:
      - ./front-gateway/src:/home/nodejs/app/src
    environment:
      NODE_ENV: local
    command: bash -c "npm install --silent && npm run build:dev& npm run start:dev" 
