apartments-api:
  image: dorbel/apartments-api
  ports:
    - '3000:3000'
  volumes:
    - ./apartments-api/src:/home/nodejs/app/src
  environment:
    NODE_ENV: test
    RDS_HOSTNAME: 127.0.0.1
    RDS_DB_NAME: circle_test
    RDS_USERNAME: ubuntu
    RDS_PASSWORD: 
  command: npm run start

front-gateway:
  image: dorbel/front-gateway
  ports:
    - '3001:3001'
  links:
    - apartments-api
  volumes:
    - ./front-gateway/src:/home/nodejs/app/src
  environment:
    APARTMENTS_API_URL: http://apartments-api:3000
    NODE_ENV: test
  command: bash -c "npm run build& npm run start" 
