# This file is meant to extend docker-compose.yml for development environment
version: '2'
services:

  apartments-api:
    build:
      dockerfile: Dockerfile.dev  
    image: dorbel/apartments-api:local
    ports:
      - '5858:5858'
    volumes:
      - ./apartments-api/src:/home/nodejs/app/src
    environment:
      NODE_ENV: local
    command: npm run start:dev

  front-gateway:
    build:
      dockerfile: Dockerfile.dev  
    image: dorbel/front-gateway:local
    ports:
      - '5859:5859'
      - '8888:8888'
    volumes:
      - ./front-gateway/src:/home/nodejs/app/src
    environment:
      NODE_ENV: local
    command: bash -c "npm run build:dev& npm run start:dev" 
