version: '2'
services:
  db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dorbel
      MYSQL_USER: dorbel
      MYSQL_PASSWORD: dorbel
  apartments-api:
    image: 'dorbel/apartments-api:develop'
    ports:
      - 3000
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: test
      RDS_HOSTNAME: db
      RDS_DB_NAME: dorbel
      RDS_USERNAME: dorbel
      RDS_PASSWORD: dorbel
  front-gateway:
    image: 'dorbel/front-gateway:develop'
    ports:
      - 3001
    depends_on:
      - apartments-api
    links:
      - apartments-api
    environment:
      NODE_ENV: test
      AUTH0_DOMAIN: dorbel-dev.eu.auth0.com
      AUTH0_CLIENT_ID: n0kP3YCZ0uOP0JBpGmrcYvBUwNtdApBL
      APARTMENTS_API_URL: 'http://apartments-api:3000'
