branch-defaults:
  default:
    environment: apartments-api-develop
    group_suffix: null
global:
  application_name: apartments-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.11.2
  default_region: eu-west-1
  profile: null
  repository: null
  sc: null
