'use strict';
const _ = require('lodash');

function getModelFieldNames(model) {
  return _(model.rawAttributes).reject('_autoGenerated').map('fieldName').value();
}

module.exports = {
  getModelFieldNames
};
