# Image to pull.
FROM node:4

# Working directory environment variable.
ENV WORKDIR="/home/nodejs/app"

# Create working directory in container.
RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR

# Install dependencies before to cache node_modules.
COPY package.json $WORKDIR
RUN npm install --silent

# Copy all files from host to container.
COPY . $WORKDIR

# Open port
EXPOSE 3002

# Run node server.
CMD [ "npm", "start" ]

# Health check for running server
HEALTHCHECK CMD curl --fail http://localhost:3002/swagger || exit 1  
